spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_db_files/bbookk
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      settings:
        web-allow-others: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

#values
apis:
  kakao:
    restApiKey: de56b657ef46f3b99834428dc7d579df

